# Generated by Django 3.1 on 2020-09-17 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionHospitalaria', '0002_auto_20200917_0118'),
    ]

    operations = [
        migrations.CreateModel(
            name='especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Ingrese el nombre de la especialidad (p. ej. Neurología, Traumatología etc.)', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='especialidad',
            field=models.ManyToManyField(help_text='Seleccione una especialidad', to='appGestionHospitalaria.especialidad'),
        ),
    ]
