# Generated by Django 3.1 on 2020-09-17 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionHospitalaria', '0003_auto_20200917_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='especialidad',
            old_name='Name',
            new_name='name',
        ),
    ]
