# Generated by Django 3.1 on 2020-10-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionHospitalaria', '0003_auto_20201004_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='especialidad',
            field=models.ManyToManyField(help_text='Seleccione una especialidad', to='appGestionHospitalaria.Especialidad'),
        ),
    ]
