# Generated by Django 3.1 on 2020-10-05 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionHospitalaria', '0005_auto_20201004_1923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={},
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='last_name',
        ),
    ]
