# Generated by Django 3.1.2 on 2020-10-12 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appGestionHospitalaria', '0006_auto_20201005_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudio',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appGestionHospitalaria.doctor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudio',
            name='secretary',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='obra_social',
            name='name',
            field=models.CharField(help_text='Ingrese el nombre de la obra social', max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
