# Generated by Django 3.1 on 2020-09-18 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionHospitalaria', '0007_patient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='obra_Social',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
