# Generated by Django 3.0.8 on 2020-10-22 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionHospitalaria', '0007_auto_20201011_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudio',
            name='date',
        ),
        migrations.RemoveField(
            model_name='estudio',
            name='name',
        ),
        migrations.RemoveField(
            model_name='estudio',
            name='time_long',
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('estudio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='appGestionHospitalaria.Estudio')),
                ('date', models.DateField()),
                ('timeFrom', models.TimeField()),
                ('timeTo', models.TimeField()),
            ],
            options={
                'unique_together': {('estudio', 'date', 'timeFrom', 'timeTo')},
            },
        ),
        migrations.CreateModel(
            name='TipoEstudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('especialidad', models.ForeignKey(help_text='Seleccione una especialidad', on_delete=django.db.models.deletion.CASCADE, to='appGestionHospitalaria.Especialidad')),
            ],
        ),
    ]
