# Generated by Django 3.0.8 on 2020-10-22 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionHospitalaria', '0008_auto_20201022_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudio',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appGestionHospitalaria.TipoEstudio'),
            preserve_default=False,
        ),
    ]
