# Generated by Django 3.1 on 2020-09-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionHospitalaria', '0008_auto_20200917_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra_social',
            name='name',
            field=models.CharField(help_text='Ingrese el nombre de la especialidad (p. ej. Neurología, Traumatología etc.)', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='obra_Social',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
