# Generated by Django 3.1 on 2020-10-22 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionHospitalaria', '0009_estudio_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudio',
            old_name='type',
            new_name='tipo',
        ),
    ]
