# Generated by Django 3.1 on 2020-10-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionHospitalaria', '0010_auto_20201022_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoestudio',
            name='duration',
        ),
        migrations.AlterField(
            model_name='turno',
            name='timeTo',
            field=models.TimeField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='turno',
            unique_together=set(),
        ),
    ]
