# Generated by Django 3.0.8 on 2020-11-25 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionHospitalaria', '0013_auto_20201023_0045'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGestionHospitalaria.Turno')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGestionHospitalaria.Estudio')),
            ],
        ),
    ]
