# Generated by Django 3.1 on 2020-11-27 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionHospitalaria', '0014_auto_20201126_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='especialidad',
        ),
        migrations.AddField(
            model_name='doctor',
            name='especialidad',
            field=models.ManyToManyField(to='appGestionHospitalaria.Especialidad'),
        ),
    ]
