# Generated by Django 3.0.8 on 2020-11-25 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionHospitalaria', '0014_historiaclinica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiaclinica',
            name='estudio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGestionHospitalaria.Estudio'),
        ),
        migrations.AlterField(
            model_name='historiaclinica',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGestionHospitalaria.Turno'),
        ),
    ]
