# Generated by Django 3.0.8 on 2020-11-25 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionHospitalaria', '0015_auto_20201125_0209'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoriaClinica',
        ),
    ]
