# Generated by Django 3.0.8 on 2020-11-28 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionHospitalaria', '0016_diajornada_turnojornada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='turnojornada',
            name='dia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appGestionHospitalaria.DiaJornada'),
        ),
        migrations.AlterField(
            model_name='turnojornada',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appGestionHospitalaria.Doctor'),
        ),
        migrations.AlterField(
            model_name='turnojornada',
            name='horario_fin',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='turnojornada',
            name='horario_inicio',
            field=models.TimeField(null=True),
        ),
    ]
