# Generated by Django 3.0.8 on 2020-11-28 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionHospitalaria', '0015_auto_20201126_2246'),
        ('appGestionHospitalaria', '0016_delete_historiaclinica'),
    ]

    operations = [
    ]
