# Generated by Django 3.0.8 on 2020-11-28 23:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionHospitalaria', '0017_auto_20201128_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='turnojornada',
            name='dia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appGestionHospitalaria.DiaJornada'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='turnojornada',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appGestionHospitalaria.Doctor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='turnojornada',
            name='horario_fin',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='turnojornada',
            name='horario_inicio',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
