# Generated by Django 3.0.8 on 2020-11-28 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionHospitalaria', '0017_merge_20201128_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudio',
            name='diagnostic',
            field=models.CharField(default=1, help_text='Ingrese un diagnostico', max_length=100),
            preserve_default=False,
        ),
    ]
