# Generated by Django 3.0.8 on 2020-11-28 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionHospitalaria', '0018_estudio_diagnostic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudio',
            name='description',
        ),
        migrations.AddField(
            model_name='estudio',
            name='comments',
            field=models.CharField(help_text='Ingrese comentarios (Será visible para el paciente)', max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='estudio',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='diagnostic',
            field=models.CharField(help_text='Ingrese un diagnóstico (No será visible para el paciente)', max_length=1500, null=True),
        ),
    ]
