# Generated by Django 3.0.8 on 2020-11-28 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionHospitalaria', '0019_auto_20201128_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudio',
            name='comments',
            field=models.TextField(help_text='Ingrese comentarios (Será visible para el paciente)', null=True),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='diagnostic',
            field=models.TextField(help_text='Ingrese un diagnóstico (No será visible para el paciente)', null=True),
        ),
    ]
