# Generated by Django 3.0.8 on 2020-11-28 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionHospitalaria', '0020_auto_20201128_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudio',
            name='file',
        ),
        migrations.AddField(
            model_name='estudio',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EstudioFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('descripcion', models.CharField(help_text='Ingrese descriptivo del archivo', max_length=50)),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGestionHospitalaria.Estudio')),
            ],
        ),
    ]
