# Generated by Django 3.0.8 on 2020-11-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionHospitalaria', '0021_auto_20201128_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiofile',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
