# Generated by Django 3.0.8 on 2020-11-28 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionHospitalaria', '0022_auto_20201128_0148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='timeTo',
        ),
    ]
