# Generated by Django 3.0.8 on 2020-11-29 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionHospitalaria', '0018_auto_20201128_2053'),
        ('appGestionHospitalaria', '0024_auto_20201128_1911'),
    ]

    operations = [
    ]
