# Generated by Django 3.1 on 2020-12-02 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appGestionHospitalaria', '0027_auto_20201201_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudio',
            name='comments',
            field=models.TextField(blank=True, default='', help_text='Ingrese comentarios (Será visible para el paciente)', null=True),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='diagnostic',
            field=models.TextField(blank=True, default='', help_text='Ingrese un diagnóstico (No será visible para el paciente)', null=True),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='doctor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='appGestionHospitalaria.doctor'),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='secretary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
