# Generated by Django 3.0.8 on 2020-12-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionHospitalaria', '0028_auto_20201202_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoestudio',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
