# Generated by Django 3.0.8 on 2020-12-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionHospitalaria', '0029_auto_20201203_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoestudio',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
