# Generated by Django 3.1 on 2020-12-17 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionHospitalaria', '0030_auto_20201203_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoestudio',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
